

                       09Additional Network Drivers07

0aThese are additional network drivers that you can choose:07

b44      Broadcom BCM440x family
b57      Broadcom BCM57xx "Tigon3" family
dc21x4   DEC/Intel 2104x/2114x "Tulip" family
dp83815  Natsemi 83815 "MacPHYTER" family (e.g., Netgear FA311/FA312)
e100b    Intel Pro/100 family of PCI and CardBus adapters
e1000    Intel Pro/1000 family of gigabit adapters
elpc575  3com 3c575 family of CardBus adapters
el556    3com 3c556 family of mini-PCI adapters
el90x    3com 3c59x/3c90x family of PCI and CardBus adapters
el94x    3com 3c94x/3c2000 family of gigabit adapters
fetnd    VIA VT86C100A/6102/6105 "Rhine" family (e.g., D-Link DFE-530TX)
yuknd    Marvell(R) Yukon(R) Ethernet Controller
ngrpci   Netgear FA310
pcntnd   AMD PCNet family (also VMWare)
rtsnd    Realtek RTL8139 family (e.g., D-Link DFE-530TX+)
rtgbnd   Realtek RTL8169/8110S Gigabit family
sis900   SiS 900 family

05[F1-Main] [F2-Additional Drivers] [F3-Information]07
