

                          09General Information07

This is a system for fully automating the installation of Windows 2000,
Windows XP, and Windows Server 2003.

Features include:

  * Automated install of OS, hotfixes, and applications
  * Full documentation and source code
  * Support for floppy, CD-ROM, and "nothing but net" installs
  * True unattended installation, 0cnot07 disk imaging
  * No Windows servers required; use your Unix servers instead
  * No Unix servers required; use your Windows servers after all
  * Completely free 

When you are finished setting up Unattended, you will be able to boot
any PC from a floppy, from a CD-ROM, or directly from the network,
answer a few questions, and come back an hour or two later to a
fully-installed Windows workstation.

05[F1-Main] [F2-Additional] [F3-Information]07
