#!/bin/bash

# Change to the scripts directory so paths are correct
cd "$(dirname "$0")"/..

# default values
SPIDER=""
SCRIPTLOC="scripts"
WINLANG=ENU
DRY=0

# process command line args.
while [ $# -gt 0 ]
do
  case "$1" in

    "-h"|"--help")
      echo "Usage: $0 [--check-only] [-h|--help] [-n] [-l <dir>|<file.bat>] [<winlang>|ALL|WHOLE]"
      echo
      echo "Download or check all required files for installation scripts"
      echo "by parsing *.bat scripts."
      echo
      echo "  -h, --help           Show this help message."
      echo "  -n                   Dry mode: just echo URL, don't download or check."
      echo "  --check-only         Only check URL validity, don't download."
      echo "  -l <dir>|<file.bat>  Target script folder or file. Defaults to 'scripts/'."
      echo "  <winlang>            Language code. Defaults to 'ENU'."
      echo "  WHOLE                Process all languages (mainly for --check-only)."
      exit 0
      ;;

    "--check-only")
      shift
      SPIDER="--spider"
      ;;

    "-l")
      shift
      SCRIPTLOC="$1"
      shift
      ;;

    "-n")
      shift
      DRY=1
      ;;

    *)
      WINLANG="$1"
      shift
      ;;
  esac
done

# checks
if [ ! -f "$SCRIPTLOC" ] && [ ! -d "$SCRIPTLOC" ]
then
  echo "ERROR: '$SCRIPTLOC' is neither a folder nor a file."
  exit 1
fi

REGEXFORLANG="URL\\|($WINLANG|ALL)"
if [ "$WINLANG" = "WHOLE" ]; then REGEXFORLANG="URL\\|"; fi

# list of files to work on
WFILES="$SCRIPTLOC"
if [ -d "$SCRIPTLOC" ]
then
  WFILES=$(egrep -lri "$REGEXFORLANG" $SCRIPTLOC/*.bat)
fi

wgetnberr=0
for cmdfile in $WFILES; do

  echo
  echo "Processing $cmdfile"

  for needed in $(egrep -hri "$REGEXFORLANG" $cmdfile | tr ' ' '~'); do
      url=$(echo -ne "$needed" | cut -d\| -f3 | tr '~' ' ' | perl -pe 's/[\r\n]//g;s/^ *//;s/ *$//')
      file=$(echo -ne "$needed" | cut -d\| -f4 | tr '~' ' ' | perl -pe 's/[\r\n]//g;s/^ *//;s/ *$//;s#([^/]*/?)$#lc($1)#eg')
      path=$(echo -ne "$file" | perl -pe 's#(.*/).*#$1#')

      if [ $DRY -eq 1 ]; then echo "dry: url=$url"; echo "dry: file=$file"; continue; fi

      if [ ! "$SPIDER" == "" ]; then
        wget $SPIDER "$url"
        if [ $? -ne 0 ]; then wgetnberr=$(( wgetnberr + 1 )); fi
        continue
      fi

      mkdir -p "$path"
      if [ ! -f "$file" ]; then
          if wget $SPIDER $WGET_OPS -O "$file.$$.tmp" "$url"; then
              mv "$file.$$.tmp" "$file"
          else
              rm -f "$file.$$.tmp"
              wgetnberr=$(( wgetnberr + 1 ))
          fi
      else
          touch "$file"
      fi
  done

done

echo
echo "Number of wget errors: $wgetnberr."
