      <!-- ##### Right Sidebar ##### -->


  <div class="rightSideBar doNotPrint">

  <p class="sideBarTitle">News</p>

  <div class="sideBarText"><strong>Changelog</strong><br />
    <a href="http://unattended.svn.sourceforge.net/viewvc/unattended/trunk/NEWS.txt">version 4.9</a>
  </div>
  <a href="http://sourceforge.net/news/?group_id=62053" class="more">more news &raquo;</a>

  <p class="sideBarTitle">Downloads</p>

  <div class="sideBarText"><strong>Unattended</strong><br />
    <a href="info-download.php#unattended">info</a> | <a 
       href="http://prdownloads.sourceforge.net/unattended/unattended-4.9.zip?download">download</a>
  </div>
  <div class="sideBarText"><strong>DOS bootdisks</strong><br />
    <a href="info-download.php#unattended-dosboot">info</a> | <a
       href="http://prdownloads.sourceforge.net/unattended/unattended-4.9-dosboot.zip?download" >download</a>
  </div>
  <div class="sideBarText"><strong>linux bootdisk</strong><br />
    <a href="info-download.php#unattended-linuxboot">info</a> | <a
       href="http://prdownloads.sourceforge.net/unattended/unattended-4.9-linuxboot.zip?download" >download</a>
  </div>
  <div class="sideBarText"><strong>support files</strong><br />
    <a href="info-download.php#supportfiles">info</a> | <a 
       href="info-download.php#supportfiles" >download</a></div>
        <?= $addbox ?>
  <div class="sideBarText">
<script type="text/javascript" src="http://www.ohloh.net/p/10536/widgets/project_thin_badge.js"></script>
  </div>
  <p class="sideBarTitle">Donations</p>
  <div class="sideBarText">
  <a href="http://sourceforge.net/donate/index.php?group_id=62053"><img src="http://images.sourceforge.net/images/project-support.jpg" width="88" height="32" border="0" alt="Support This Project" /> </a>
  </div>
  </div>
